//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by win32resource.rc
//
#include <windows.h>

#define IDI_ICON1                       1
#define IDC_GENERATE                    3
#define IDD_CONSOLEDIALOG               101
#define IDC_CONSOLEEDIT                 102
#define IDR_MENU1                       103
#define IDD_ABOUT                       104
#define IDD_PERFORMANCE                 111
#define IDD_HOSTDIALOG                  131
#define IDD_JOINDIALOG                  132
#define IDR_SPACESTATION                135
#define IDD_VIDEOSETUP                  136
#define IDR_ABOUT                       137
#define IDD_CUSTOMISEVEHICLE            138
#define IDD_SETUP                       139
#define IDD_CONTROLS                    140
#define IDD_REGISTER                    141
#define IDD_ENTERREGO                   142
#define IDR_REGISTER                    143
#define IDD_AUDIOSETTINGS               147
#define IDD_MAPEDITOR                   148
#define IDM_MAPEDITOR                   149
#define IDD_BOTDLG                      150
#define IDD_PROGRESS                    151
#define IDD_SELECTEDOBJECT              152
#define IDD_TIMELIMIT                   153
#define IDD_LANGUAGESELECTION           154
#define IDB_GERMAN                      155
#define IDB_ENGLISH                     157
#define IDB_DUTCH                       161
#define IDC_VERSION                     1000
#define IDC_RESOLUTION                  1001
#define IDC_FULLSCREEN                  1002
#define IDC_BITDEPTH                    1003
#define IDC_LIMITFPS                    1003
#define IDC_EDIT1                       1005
#define IDC_NAME                        1005
#define IDC_GAMENAME                    1006
#define IDC_LIST1                       1008
#define IDC_640x480                     1008
#define IDC_HOSTNAME                    1009
#define IDC_800x600                     1009
#define IDC_1024x768                    1010
#define IDC_1280x1024                   1011
#define IDC_15                          1012
#define IDC_CUSTOMISE                   1013
#define IDC_SOUNDS                      1014
#define IDC_16                          1015
#define IDC_ENABLECUSTOMISE             1016
#define IDC_24                          1017
#define IDC_IMAGE                       1018
#define IDC_32                          1019
#define IDC_CONNECT                     1020
#define IDC_RUN                         1021
#define IDC_ABOUT                       1022
#define IDC_FOG                         1023
#define IDC_SOUND                       1024
#define IDC_ENTERREGISTRATION           1025
#define IDC_REGOCODE                    1026
#define IDC_PURCHASE                    1027
#define IDC_REGONAME                    1028
#define IDC_REGTEXT                     1029
#define IDC_dasd                        1030
#define IDC_REGISTERED                  1031
#define IDC_ENABLEMUSIC                 1032
#define IDC_ENABLEMUSIC2                1033
#define IDC_ENABLEEFFECTS               1034
#define IDC_OBJECTS                     1035
#define IDC_PLANTS                      1036
#define IDC_SELECTEDITEM                1037
#define IDC_TOD                         1037
#define IDC_VEHICLES                    1038
#define IDC_XPOS                        1039
#define IDC_CHARACTER                   1039
#define IDC_SOUNDTRACK                  1039
#define IDC_PLANES                      1040
#define IDC_CHARACTER2                  1040
#define IDC_FUELECONOMY                 1041
#define IDC_YPOS                        1042
#define IDC_STRUCTURES                  1043
#define IDC_ZPOS                        1044
#define IDC_MISC                        1045
#define IDC_AMMOSTRENGTH                1046
#define IDC_MAPITEMS                    1047
#define IDC_XROT                        1048
#define IDC_TEAMS                       1049
#define IDC_AMMOCOUNT                   1050
#define IDC_YROT                        1051
#define IDC_ZROT                        1052
#define IDC_MAXRANGE                    1053
#define IDC_XROTSLIDER                  1054
#define IDC_PORT                        1055
#define IDC_YROTSLIDER                  1056
#define IDC_SUBMERGE                    1057
#define IDC_ZROTSLIDER                  1058
#define IDC_SIDE                        1059
#define IDC_ADDROTATIONSETTING          1060
#define IDC_MAXSPEED                    1061
#define IDC_ROTATIONSETTINGNAME         1062
#define IDC_MAP                         1063
#define IDC_SAVEDROTATIONS              1064
#define IDC_VEHICLENAME                 1065
#define IDC_LIGHTING                    1066
#define IDC_XSCALE                      1067
#define IDC_POINTS                      1068
#define IDC_YSCALE                      1069
#define IDC_I1                          1070
#define IDC_SHELLS                      1070
#define IDC_ZSCALE                      1071
#define IDC_I2                          1072
#define IDC_BOMBS                       1072
#define IDC_XSCALESLIDER                1073
#define IDC_I3                          1074
#define IDC_YSCALESLIDER                1075
#define IDC_I4                          1076
#define IDC_ZSCALESLIDER                1077
#define IDC_I5                          1078
#define IDC_ADDSCALESETTING             1079
#define IDC_GAME                        1080
#define IDC_SCALESETTINGNAME            1081
#define IDC_LIGHTING2                   1082
#define IDC_GAMETYPE                    1083
#define IDC_SAVEDSCALES                 1084
#define IDC_GAME2                       1085
#define IDC_SAVE                        1086
#define IDC_AITYPE                      1087
#define IDC_SCORE                       1088
#define IDC_AITEAM                      1088
#define IDC_SAVEAS                      1089
#define IDC_GAMEIMPORTANCE              1090
#define IDC_HUGH                        1091
#define IDC_TEAM                        1092
#define IDC_MAPNAME                     1093
#define IDC_README                      1094
#define IDC_MAPNAME2                    1095
#define IDC_CREATOR                     1096
#define IDC_VIDEO                       1097
#define IDC_MAPNAME3                    1098
#define IDC_BINFILE                     1099
#define IDC_PERFORMANCE                 1100
#define IDC_QUIT                        1101
#define IDC_STRIPFILE                   1102
#define IDC_REGISTER                    1103
#define IDC_SCROLLBAR1                  1104
#define IDC_ADD                         1105
#define IDC_ADDPLANT                    1106
#define IDC_DELETE                      1107
#define IDC_LOAD                        1108
#define IDC_BUMPS                       1109
#define IDC_SLIDER1                     1110
#define IDC_NEW                         1111
#define IDC_SCALE                       1112
#define IDC_INDESTRUCTABLE              1113
#define IDC_ADDVEHICLE                  1114
#define IDC_WATER                       1115
#define IDC_ISA_AI                      1116
#define IDC_REBUILDMAP                  1117
#define IDC_ADDBOT                      1118
#define IDC_ADDPLANE                    1119
#define IDC_ADDLINEARMARKER             1120
#define IDC_ADDSTRUCTURE                1121
#define IDC_COMBO1                      1122
#define IDC_MARKERS                     1123
#define IDC_ADDMISC                     1124
#define IDC_REMOVELINEARMARKER          1125
#define IDC_ADDTEAM                     1126
#define IDC_SHOW                        1127
#define IDC_RANDOMCOUNT                 1128
#define IDC_PROGRESS1                   1129
#define IDC_CONNECTION1                 1130
#define IDC_RANDOMSCALE                 1131
#define IDC_CONNECTION2                 1132
#define IDC_LOADBITMAP                  1133
#define IDC_CONNECTION3                 1134
#define IDC_RANDOMYOFFSET               1135
#define IDC_CONNECTION4                 1136
#define IDC_RANDOMDISPERSE              1137
#define IDC_STRENGTHEDIT                1138
#define IDC_REFUEL                      1139
#define IDC_ARMORY                      1140
#define IDC_TAB1                        1140
#define IDC_REPAIRS                     1141
#define IDC_AI1                         1141
#define IDC_AI2                         1142
#define IDC_ENGLISH                     1142
#define IDC_AI3                         1143
#define IDC_GERMAN                      1143
#define IDC_DUTCH                       1144
#define ID_FILE_NEWGAME                 40001
#define ID_FILE_HOSTGAME                40001
#define ID_FILE_QUIT                    40003
#define ID_VIEW_FULLSCREEN              40004
#define ID_HELP_ABOUT                   40005
#define ID_VIEW_RESOLUTION_640X480      40007
#define ID_VIEW_RESOLUTION_800X600      40008
#define ID_VIEW_RESOLUTION_1024X768     40009
#define ID_VIEW_RESOLUTION_1280X1024    40010
#define ID_VIEW_FOG                     40011
#define IDM_TESTSPEED                   40012
#define ID_FILE_JOINGAME                40013
#define IDM_NIGHT                       40014
#define IDM_MORNING                     40015
#define IDM_AFTERNOON                   40016
#define IDM_TWILIGHT                    40017
#define IDM_MIDNIGHT                    40018
#define IDM_PITCHBLACK                  40019
#define IDM_HOST                        40020
#define IDM_JOIN                        40021
#define IDM_ABOUT                       40022
#define ID_HELP_CONTROLS                40023
#define IDM_MANUAL                      40024
#define IDM_VIDEOSETTINGS               40025
#define IDM_SINGLEPLAYER                40026
#define IDC_SHOWAGAIN                   40027
#define ID_HELP_MANUAL                  40027
#define IDC_TLMESSAGE                   40028
#define IDM_DOWNLOAD                    40029
#define IDC_LABEL2                      40030
#define IDM_HELP                        40031
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
