#ifndef _WIN32_LANGUAGESTRINGS_H_

//==========================================================================

#define kNumStrings				200
#define kNumLanguages			4

extern const char* _strings[kNumStrings][kNumLanguages];

#define STR( id )	_strings[id][languageId]
#define LEN( id )	strlen(_strings[id][languageId])

//==========================================================================

#define strLoadingObjects			0
#define strAboutScreen				1
#define strDownloadScreen			2
#define strAreYouSureClient			3
#define strWarning					4
#define strAreYouSureServer			5
#define strAreYouSureSinglePlayer	6
#define strError					7
#define strJoined					8
#define strNameTaken				9
#define strGameFull					10
#define strNoMap					11
#define strNoSlotRed				12
#define strNoSlotGreen				13
#define strNoSlotBlue				14
#define strNoSlotYellow				15
#define strChooseOtherTeam			16
#define strIncorrectVersion			17
#define strIsJoining				18
#define strQuit						19
#define strServerRefused			20
#define strServerQuit				21
#define strGameControls				22
#define strMirrorMouse				23
#define strCustomise				24
#define strTurnLeft					25
#define strTurnRight				26
#define strForwards					27
#define strBackwards				28
#define strJump						29
#define strFire						30
#define strInGameMap				31
#define strOK						32
#define strReturnToGame				33
#define strDownload					34
#define strEnterRego				35
#define strHelp						36
#define strManual					37
#define strShowTips					38
#define strEmailHelp				39
#define strCancel					40
#define strHostSettings				41
#define strName						42
#define strGameName					43
#define strTCPIPPort				44
#define strCharacter				45
#define strMap						46
#define strGameType					47
#define strTeam						48
#define strStartHost				49
#define strHostDetails				50
#define strGameType1				51
#define strGameType2				52
#define strRedTeam					53
#define strGreenTeam				54
#define strBlueTeam					55
#define strYellowTeam				56
#define strJoinExisting				57
#define strHostName					58
#define strConnect					59
#define strSearchForGames			60
#define strJoin						61
#define strNoGamesFound				62
#define strServerNotResponding		63
#define strSinglePlayer				64
#define strStart					65
#define strSettings					66
#define strResolution				67
#define strLanguage					68
#define strMusicVolume				69
#define strSoundVolume				70
#define strPerformance				71
#define strLowSpec					72
#define strHighSpec					73
#define strPlayMusic				74
#define strPlaySounds				75
#define strVideo					76
#define strAudio					77
#define strFullscreen				78
#define strLimitFPS					79
#define strAntiAlias				80
#define strEnglish					81
#define strGerman					82
#define strArabic					83
#define strDutch					84
#define strFrench					85
#define strEnterName				86
#define strThanksForRegistering		87
#define strThankYou					88
#define strIncorrectCode			89
#define strRegistration				90
#define strCode						91
#define strShowTipsAtStartup		92
#define strClose					93
#define strTips						94
#define strRefusedConnection		95
#define strCouldNotConnect			96
#define strYes						97
#define strNo						98
#define strPressAnyKey				99
#define strInstructions1			100
#define strbLeftMouse				101
#define strbRightMouse				102
#define strbCancel					103
#define strbMiddleMouse				104
#define strbBack					105
#define strbTab						106
#define strbCLR						107
#define strbEnter					108
#define strbMenu					109
#define strbPause					110
#define strbCaps					111
#define strbEscape					112
#define strbConvert					113
#define strbNonConvert				114
#define strbAccept					115
#define strbModeChange				116
#define strbSpaceBar				117
#define strbPrior					118
#define strbNext					119
#define strbEnd						120
#define strbHome					121
#define strbLeft					122
#define strbUp						123
#define strbRight					124
#define strbDown					125
#define strbSelect					126
#define strbPrint					127
#define strbExec					128
#define strbScreenshot				129
#define strbInsert					130
#define strbDel						131
#define strbHelp					132
#define strbPlay					133
#define strbZoom					134
#define strbNoName					135
#define strWGI						136
#define strReject					137
#define strAccept					138
#define strUnregistered				139
#define strOnlyRegistered			140
#define strJan						141
#define strFeb						142
#define strMar						143
#define strApr						144
#define strMay						145
#define strJun						146
#define strJul						147
#define strAug						148
#define strSep						149
#define strOct						150
#define strNov						151
#define strDec						152
#define strProgramWillExpire		153
#define strHasExpired				154
#define strNoOpenGL					155
#define strSaveChanges				156
#define strRegisteredTo				157
#define strPleaseWait				158
#define strHasExpired2				159
#define strEvalExpired1				160
#define strEvalExpired2				161
#define strSetup					162
#define strHostNetworkGame			163
#define strJoinNetworkGame			164
#define strControls					165
#define strAbout					166
#define strDownloadExtras			167
#define strExit						168
#define strShadowNone				169
#define strShadowGood				170
#define strShadowBest				171

//==========================================================================

#endif
